### ISSUE TITLE
[enhancement] add the original author and message in the message sent by the bot when the original message is deleted

### ISSUE THREAD

**Issue by Butterroach** [spongedsc/SpongeChat#24]
currently if the message the bot is trying to reply to doesn't exist you simply just send the message

it would be better to add the author's username and message in a quote block if the original message was deleted before the bot could reply, to avoid confusion

a format like this is good:

```
> [username]: [message]
[message generated by spongechat]
```

***\*\*\*(MAKE SURE TO PUT A `>` AT THE START OF EACH NEW LINE IN THE MESSAGE OR ELSE FORMATTING WOULD BREAK!!!!!)\*\*\****

or if you're too lazy to do that:

````
```
[username]: [message]
```
[message generated by spongechat]
````

**Comment by artificialbutter** [comment]
speedrun

**Comment by artificialbutter** [comment]
cock dick balls :trollface:

**Comment by artificialbutter** [comment]
how about people don't delete messages how about that

**Comment by artificialbutter** [comment]
(working on it)

**Comment by Butterroach** [comment]
> (working on it) (im not)

How is it that hard I did not expect this issue to be up for 12 days

**Comment by Butterroach** [comment]
That commit should've worked I don't understand

**Comment by artificialbutter** [comment]
it just can't detect if a message is deleted or not properly, and i don't know how to do that

**Comment by artificialbutter** [comment]
> How is it that hard I did not expect this issue to be up for 12 days

@Butterroach 83 days

**Comment by Butterroach** [comment]
> @Butterroach 83 days

![home-accents-holiday-christmas-yard-decorations-23rt26823142-64_300.jpg](https://github.com/artificialbutter/SpongeChat/assets/111113093/927f7cc4-45cc-400f-a315-e82c2f4db982)

**Comment by artificialbutter** [comment]
can we kill butterroach for making me do work

**Comment by artificialbutter** [comment]
> Just put a wontfix label

no thats cheating

**Comment by Butterroach** [comment]
It's just an enhancement...come on....do it...

**Comment by Butterroach** [comment]
@lordsirggg do this

**Comment by lordsirggg** [comment]
Glart

**Comment by artifishvr** [comment]
@OcaMinty HELPA

**Comment by artifishvr** [comment]
@daniwasonline pls fix

**Comment by daniwasonline** [comment]
nts:
- check if message continues to exist before sending
- if it does, send
- if it doesn't, send this fallback

**Comment by artifishvr** [comment]
i tried that but couldnt make it work you do it

**Comment by OcaMinty** [comment]
hi! you can fix this issue by never sending the message under any circumstances! happy to help.

**Comment by daniwasonline** [comment]
> i tried that but couldnt make it work you do it
> 
> 

I wrote it as a note to self. I'll work on this tonight



emergency crewmate meeting sus!

**Comment by Butterroach** [comment]
race (i will try to do it first)

**Comment by daniwasonline** [comment]
> race (i will try to do it first)

If you could, that would be fantastic




sussy baka amogus livvy dunne and baby gronk rizzler

**Comment by artifishvr** [comment]
AGAIN!

**Comment by lordsirggg** [comment]
I’m busting in creaming

**Comment by lordsirggg** [comment]
Im*

**Comment by Butterroach** [comment]
> AGAIN!

![90](https://github.com/spongedsc/SpongeChat/assets/111113093/24b05432-225b-44d7-a1da-d5cd775fe5df)

**Comment by Butterroach** [comment]
what have i done

**Comment by lordsirggg** [comment]
Can we have gay sex

**Comment by Butterroach** [comment]
fuck it this is never getting fixed

**Comment by artifishvr** [comment]
it has to be done now

**Comment by artifishvr** [comment]
took 138 days

**Comment by artifishvr** [comment]
still has issues lets fix it in v2
