### ISSUE TITLE
[v2] Create the actual base, womp womp

### ISSUE THREAD

**Issue by daniwasonline** [spongedsc/SpongeChat#48]
Fork/create a new branch, clear the entire slate, create the new base and write some docs on how to run the new base. Expect some pretty different things with the workflow versus standard Node.js.

(Not sure if I'll use swc or Babel right now, likely the former?)

**Comment by Butterroach** [comment]
![image_proxy](https://github.com/spongedsc/SpongeChat/assets/111113093/c9ba7143-57c4-4df5-b528-c90fa4395020)

**Comment by daniwasonline** [comment]
Implemented as part of #55 (commit: 99734d315c425b45219a80f077b96e70a35ecbca)
