### ISSUE TITLE
Handling logs & long messages on mobile

### ISSUE THREAD

**Issue by daniwasonline** [spongedsc/SpongeChat#68]
Given that markdown files don't have a preview in (stock) mobile Discord, a portion of our userbase is unable to easily access certain vital functions of SpongeChat. A solution to this may be to automatically upload generated logs/logged messages to a webserver (chibisafe or paste.ee?) and include a link with these types of markdown documents.

**Comment by artifishvr** [comment]
Should we include a barebones paste server in the docker-compose and have an env variable to configure the domain? I feel like that would make the most sense.

**Comment by artifishvr** [comment]
https://github.com/w4/bin currently looks like the best choice to me

**Comment by daniwasonline** [comment]
> Should we include a barebones paste server in the docker-compose and have an env variable to configure the domain? I feel like that would make the most sense.

I think this would make sense -- o r, we could build our own? I think that could be nice, having a web interface for logs. It sounds very overkill, but it would also mean that we wouldn't have to expose a public API for uploads - the application would directly write to a database that the log server can read from.

**Comment by daniwasonline** [comment]
> I think this would make sense -- o r, we could build our own? I think that could be nice, having a web interface for logs. It sounds very overkill, but it would also mean that we wouldn't have to expose a public API for uploads - the application would directly write to a database that the log server can read from.

And yes, this would be an excuse for me to add some sort of web thing to the project. _What can I say? I'm a soydev (;_

**Comment by artifishvr** [comment]
> > I think this would make sense -- o r, we could build our own? I think that could be nice, having a web interface for logs. It sounds very overkill, but it would also mean that we wouldn't have to expose a public API for uploads - the application would directly write to a database that the log server can read from.
> 
> And yes, this would be an excuse for me to add some sort of web thing to the project. _What can I say? I'm a soydev (;_

I'd prefer having an open api or forking an existing pastebin than having another project for the two-js-dev (with only one good one) team to maintain.

**Comment by daniwasonline** [comment]
> > > I think this would make sense -- o r, we could build our own? I think that could be nice, having a web interface for logs. It sounds very overkill, but it would also mean that we wouldn't have to expose a public API for uploads - the application would directly write to a database that the log server can read from.
> > 
> > 
> > And yes, this would be an excuse for me to add some sort of web thing to the project. _What can I say? I'm a soydev (;_
> 
> I'd prefer having an open api or forking an existing pastebin than having another project for the two-js-dev (with only one good one) team to maintain.

Fair point. We could probably create a separate pastebin viewer that's specifically for the log as well.

(also fym "one good [js dev]")

**Comment by artifishvr** [comment]
> (also fym "one good [js dev]")

you

**Comment by daniwasonline** [comment]
> > (also fym "one good [js dev]")
> 
> you

stfu

**Comment by artifishvr** [comment]
nvm, bin doesn't seem to have persistence

**Comment by artifishvr** [comment]
https://github.com/matze/wastebin <= i like the design of this one
https://github.com/WardPearce/paaster?tab=readme-ov-file
